### PR TITLE
test: add-user-model-test

### PR DESCRIPTION
**Pull request by Jyunri**
Issue #12

Add tests for user model.
PS: I noticed that there are some constraints present on database that are not in the model(s). I can contribute later on this if it is reasonable :smile:

### CODE REVIEW

**Review by nwarwick — APPROVED** [review]
Thank you @Jyunri!

**Comment by nwarwick** [comment]
@Jyunri Adding the missing constraints to the models would be appreciated as well 😇

**Comment by Jyunri** [comment]
@nwarwick  do you mind if I add rspec (for better testing workspace) and pry-rails (for debugging) on the project?

**Comment by nwarwick** [comment]
@Jyunri `pry-rails` you can add for sure! As for transitioning to Rspec, I'm not sure if I'm totally sold on the idea, considering the size of the project. Not sure if it justifies a more advanced testing setup.

**Pull request merged**
